### ISSUE TITLE
identical simulations

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Felodipine-Model#4]
No difference between some simulations under **Test** and under **PI**.
Why do we need identical simulatins in the project?

![grafik](https://user-images.githubusercontent.com/25061876/185798472-d0619e85-b930-4f32-89fa-a4d4bbadd654.png)

**Comment by JustineHenriot** [comment]
Simulations in PI and Test folders don't use the same observed data.
The ones in the PI folder were used for model building, the ones in the Test folder for model verification.
